select * from USER_ U

JOIN BASKET B on B.USERID = U.ID
JOIN BASKETDETAIL BD on BD.ID = U.ID
JOIN CITY C on C.ID = U.ID
JOIN DISTRICT D on D.ID = U.ID
JOIN ITEM I on I.ID = U.ID


where U.ID = 7076

-- Yeni Örnek --

select U.NAMESURNAME, B.CREATEDDATE, BD.AMOUNT, BD.PRICE, BD.TOTAL, I.ITEMNAME, I.ITEMCODE, I.CATEGORY1, I.CATEGORY2, I.CATEGORY3, A.ADDRESSTEXT
, C.CITY, T.TOWN, D.DISTRICT  from USER_ U

JOIN BASKET B on B.USERID = U.ID
JOIN BASKETDETAIL BD on BD.ID = U.ID
JOIN DISTRICT D on D.ID = U.ID
JOIN ITEM I on I.ID = U.ID
JOIN ORDER_ O on O.ID = B.USERID
JOIN ADDRES A on A.ID = O.USERID
JOIN CITY C on C.ID = A.CITYID
JOIN TOWN T on T.ID = A.CITYID

select * from BASKETDETAIL


